--------------------------------------------------------
--  Fichier créé - jeudi-mai-06-2021   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table CHAMBRES
--------------------------------------------------------

  CREATE TABLE "IHEB"."CHAMBRES" 
   (	"NUM" NUMBER, 
	"NOM" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table ENFANT
--------------------------------------------------------

  CREATE TABLE "IHEB"."ENFANT" 
   (	"ID_ENFANT" NUMBER, 
	"NOM" VARCHAR2(20 BYTE), 
	"PRENOM" VARCHAR2(20 BYTE), 
	"DATEDENAISSANCE" DATE, 
	"SEXE" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table ETAGES
--------------------------------------------------------

  CREATE TABLE "IHEB"."ETAGES" 
   (	"NUM_ETAGE" NUMBER, 
	"TYPE" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table ETAT
--------------------------------------------------------

  CREATE TABLE "IHEB"."ETAT" 
   (	"ID_ETAT" NUMBER, 
	"NOM" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table LIEU_ATTRACTION
--------------------------------------------------------

  CREATE TABLE "IHEB"."LIEU_ATTRACTION" 
   (	"ID" VARCHAR2(20 BYTE), 
	"NOM" VARCHAR2(20 BYTE), 
	"ADRESSE" VARCHAR2(20 BYTE), 
	"TYPE" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table LOISIR
--------------------------------------------------------

  CREATE TABLE "IHEB"."LOISIR" 
   (	"ID_LOISIR" NUMBER, 
	"LIEU" VARCHAR2(20 BYTE), 
	"DATE_LOISIR" DATE, 
	"TYPE" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table MODEE
--------------------------------------------------------

  CREATE TABLE "IHEB"."MODEE" 
   (	"ID_MODE" NUMBER, 
	"COLUMN1" VARCHAR2(20 BYTE), 
	"ETAT" VARCHAR2(20 BYTE), 
	"DATE_DÉBUT" DATE, 
	"DATE_FIN" DATE, 
	"DESCRIPTION" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PROFIL
--------------------------------------------------------

  CREATE TABLE "IHEB"."PROFIL" 
   (	"ID_PROFIL" NUMBER, 
	"NOM" VARCHAR2(20 BYTE), 
	"PRÉNOM" VARCHAR2(20 BYTE), 
	"TYPE" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table TRANCHEDAGE
--------------------------------------------------------

  CREATE TABLE "IHEB"."TRANCHEDAGE" 
   (	"NIVEAU" NUMBER, 
	"AGE" NUMBER, 
	"CLASSE" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table UTILISATEURS
--------------------------------------------------------

  CREATE TABLE "IHEB"."UTILISATEURS" 
   (	"ID" NUMBER, 
	"NOM" VARCHAR2(20 BYTE), 
	"PRENOM" VARCHAR2(20 BYTE), 
	"NUM_TEL" NUMBER, 
	"ADRESSE" VARCHAR2(20 BYTE), 
	"EMAIL" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into IHEB.CHAMBRES
SET DEFINE OFF;
Insert into IHEB.CHAMBRES (NUM,NOM) values ('4','chambre filles');
Insert into IHEB.CHAMBRES (NUM,NOM) values ('1','salon');
Insert into IHEB.CHAMBRES (NUM,NOM) values ('2','salon2');
Insert into IHEB.CHAMBRES (NUM,NOM) values ('3','chambre garÃ§ons');
Insert into IHEB.CHAMBRES (NUM,NOM) values ('5','chambre parents');
Insert into IHEB.CHAMBRES (NUM,NOM) values ('6','chambre grandparents');
Insert into IHEB.CHAMBRES (NUM,NOM) values ('7','cuisine');
Insert into IHEB.CHAMBRES (NUM,NOM) values ('8','salle de bain');
Insert into IHEB.CHAMBRES (NUM,NOM) values ('9','toilettes');
Insert into IHEB.CHAMBRES (NUM,NOM) values ('14','pppp');
Insert into IHEB.CHAMBRES (NUM,NOM) values ('10','pppp');
Insert into IHEB.CHAMBRES (NUM,NOM) values ('19','adult');
Insert into IHEB.CHAMBRES (NUM,NOM) values ('7777777','zzzzzzzzz');
Insert into IHEB.CHAMBRES (NUM,NOM) values ('0',null);
REM INSERTING into IHEB.ENFANT
SET DEFINE OFF;
REM INSERTING into IHEB.ETAGES
SET DEFINE OFF;
Insert into IHEB.ETAGES (NUM_ETAGE,TYPE) values ('3','nuit pour parents');
Insert into IHEB.ETAGES (NUM_ETAGE,TYPE) values ('999','aaa');
Insert into IHEB.ETAGES (NUM_ETAGE,TYPE) values ('1','iheb22');
Insert into IHEB.ETAGES (NUM_ETAGE,TYPE) values ('2','nuit');
Insert into IHEB.ETAGES (NUM_ETAGE,TYPE) values ('88','mmm');
Insert into IHEB.ETAGES (NUM_ETAGE,TYPE) values ('9990','aaa');
Insert into IHEB.ETAGES (NUM_ETAGE,TYPE) values ('8','ppp');
Insert into IHEB.ETAGES (NUM_ETAGE,TYPE) values ('13','etage adult');
Insert into IHEB.ETAGES (NUM_ETAGE,TYPE) values ('888','aaaaaaaa');
Insert into IHEB.ETAGES (NUM_ETAGE,TYPE) values ('0',null);
REM INSERTING into IHEB.ETAT
SET DEFINE OFF;
REM INSERTING into IHEB.LIEU_ATTRACTION
SET DEFINE OFF;
Insert into IHEB.LIEU_ATTRACTION (ID,NOM,ADRESSE,TYPE) values ('2','aaammmmmmmmmmm','aaaaaa','Sport');
REM INSERTING into IHEB.LOISIR
SET DEFINE OFF;
REM INSERTING into IHEB.MODEE
SET DEFINE OFF;
REM INSERTING into IHEB.PROFIL
SET DEFINE OFF;
REM INSERTING into IHEB.TRANCHEDAGE
SET DEFINE OFF;
REM INSERTING into IHEB.UTILISATEURS
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index PROFIL_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "IHEB"."PROFIL_PK" ON "IHEB"."PROFIL" ("ID_PROFIL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index UTILISATEURS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "IHEB"."UTILISATEURS_PK" ON "IHEB"."UTILISATEURS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index MODEE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "IHEB"."MODEE_PK" ON "IHEB"."MODEE" ("ID_MODE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index LOISIR_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "IHEB"."LOISIR_PK" ON "IHEB"."LOISIR" ("ID_LOISIR") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index ENFANT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "IHEB"."ENFANT_PK" ON "IHEB"."ENFANT" ("ID_ENFANT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index ETAT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "IHEB"."ETAT_PK" ON "IHEB"."ETAT" ("ID_ETAT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index ETAGES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "IHEB"."ETAGES_PK" ON "IHEB"."ETAGES" ("NUM_ETAGE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index LIEU_ATTRACTION_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "IHEB"."LIEU_ATTRACTION_PK" ON "IHEB"."LIEU_ATTRACTION" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index TRANCHEDAGE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "IHEB"."TRANCHEDAGE_PK" ON "IHEB"."TRANCHEDAGE" ("NIVEAU") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index CHAMBRES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "IHEB"."CHAMBRES_PK" ON "IHEB"."CHAMBRES" ("NUM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table LIEU_ATTRACTION
--------------------------------------------------------

  ALTER TABLE "IHEB"."LIEU_ATTRACTION" ADD CONSTRAINT "LIEU_ATTRACTION_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "IHEB"."LIEU_ATTRACTION" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table MODEE
--------------------------------------------------------

  ALTER TABLE "IHEB"."MODEE" ADD CONSTRAINT "MODEE_PK" PRIMARY KEY ("ID_MODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "IHEB"."MODEE" MODIFY ("ID_MODE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table LOISIR
--------------------------------------------------------

  ALTER TABLE "IHEB"."LOISIR" ADD CONSTRAINT "LOISIR_PK" PRIMARY KEY ("ID_LOISIR")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "IHEB"."LOISIR" MODIFY ("ID_LOISIR" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ETAT
--------------------------------------------------------

  ALTER TABLE "IHEB"."ETAT" ADD CONSTRAINT "ETAT_PK" PRIMARY KEY ("ID_ETAT")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "IHEB"."ETAT" MODIFY ("ID_ETAT" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PROFIL
--------------------------------------------------------

  ALTER TABLE "IHEB"."PROFIL" ADD CONSTRAINT "PROFIL_PK" PRIMARY KEY ("ID_PROFIL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "IHEB"."PROFIL" MODIFY ("ID_PROFIL" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TRANCHEDAGE
--------------------------------------------------------

  ALTER TABLE "IHEB"."TRANCHEDAGE" ADD CONSTRAINT "TRANCHEDAGE_PK" PRIMARY KEY ("NIVEAU")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "IHEB"."TRANCHEDAGE" MODIFY ("NIVEAU" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table UTILISATEURS
--------------------------------------------------------

  ALTER TABLE "IHEB"."UTILISATEURS" ADD CONSTRAINT "UTILISATEURS_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "IHEB"."UTILISATEURS" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ETAGES
--------------------------------------------------------

  ALTER TABLE "IHEB"."ETAGES" ADD CONSTRAINT "ETAGES_PK" PRIMARY KEY ("NUM_ETAGE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "IHEB"."ETAGES" MODIFY ("NUM_ETAGE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ENFANT
--------------------------------------------------------

  ALTER TABLE "IHEB"."ENFANT" ADD CONSTRAINT "ENFANT_PK" PRIMARY KEY ("ID_ENFANT")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "IHEB"."ENFANT" MODIFY ("ID_ENFANT" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CHAMBRES
--------------------------------------------------------

  ALTER TABLE "IHEB"."CHAMBRES" ADD CONSTRAINT "CHAMBRES_PK" PRIMARY KEY ("NUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "IHEB"."CHAMBRES" MODIFY ("NUM" NOT NULL ENABLE);
